# version: '3.9'
# services:
#   postgres:
#     image: postgres:16
#     restart: always
#     environment:
#       POSTGRES_DB: restaurant
#       POSTGRES_USER: restaurant
#       POSTGRES_PASSWORD: restaurant
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#
# volumes:
#   postgres_data:


